
FROM python:3.9-slim


WORKDIR /app


COPY requirements.txt /app/


RUN pip install --trusted-host pypi.python.org -r requirements.txt


COPY . /app


EXPOSE 5000


ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0


CMD ["flask", "run"]
